//! RNG conformance: the Rust port of xorshift7 + `integer()` must reproduce
//! naive's streams byte-for-byte. The fixture was generated by
//! `tests/fixtures/generate_rng_fixture.mjs` from the repo-pinned
//! `esm-seedrandom` and naive's `executing/random.ts`.

mod common;

use common::*;
use dicexp_nova_builtins::testutil as tu;

const FIXTURE: &str = include_str!("fixtures/rng_fixture.txt");

#[test]
fn uint32_streams_match_naive() {
    setup();
    for line in FIXTURE.lines() {
        let mut parts = line.split_whitespace();
        if parts.next() != Some("u32") {
            continue;
        }
        let seed: i32 = parts.next().expect("seed").parse().expect("i32 seed");
        let expected: Vec<u32> = parts
            .next()
            .expect("values")
            .split(',')
            .map(|s| s.parse().expect("u32"))
            .collect();
        tu::rng_seed(seed);
        for (i, want) in expected.iter().enumerate() {
            let got = tu::rng_next_u32();
            assert_eq!(got, *want, "seed {seed} draw {i}");
        }
    }
}

#[test]
fn integer_streams_match_naive() {
    setup();
    for line in FIXTURE.lines() {
        let mut parts = line.split_whitespace();
        if parts.next() != Some("int") {
            continue;
        }
        let seed: i32 = parts.next().expect("seed").parse().expect("i32 seed");
        let lower: i64 = parts.next().expect("lower").parse().expect("i64 lower");
        let upper: i64 = parts.next().expect("upper").parse().expect("i64 upper");
        let expected: Vec<i64> = parts
            .next()
            .expect("values")
            .split(',')
            .map(|s| s.parse().expect("i64"))
            .collect();
        tu::rng_seed(seed);
        for (i, want) in expected.iter().enumerate() {
            let got = tu::rng_integer(lower, upper);
            assert_eq!(got, *want, "seed {seed} integer({lower}, {upper}) draw {i}");
        }
    }
}
