/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    CommonOptionalNumberInput: typeof import('./src/components/common/optional-number-input.vue')['default']
    CommonSkeleton: typeof import('./src/components/common/skeleton.vue')['default']
    DicexpEditor: typeof import('./src/components/dicexp-editor.vue')['default']
    LayoutHeader: typeof import('./src/components/layout/header.vue')['default']
    RestrictionsPane: typeof import('./src/components/restrictions-pane.vue')['default']
    ResultPane: typeof import('./src/components/result-pane/result-pane.vue')['default']
    ResultPaneTabRepresentation: typeof import('./src/components/result-pane/tab-representation.vue')['default']
    ResultPaneTabResult: typeof import('./src/components/result-pane/tab-result.vue')['default']
  }
}
