/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    DicexpEditor: typeof import('./src/components/dicexp-editor.vue')['default']
    LayoutHeader: typeof import('./src/components/layout-header.vue')['default']
    OptionalNumberInput: typeof import('./src/components/optional-number-input.vue')['default']
    RestrictionsPane: typeof import('./src/components/restrictions-pane.vue')['default']
    ResultPane: typeof import('./src/components/result-pane.vue')['default']
    ResultPaneTabRepresentation: typeof import('./src/components/result-pane-tab-representation.vue')['default']
    ResultPaneTabResult: typeof import('./src/components/result-pane-tab-result.vue')['default']
    Skeleton: typeof import('./src/components/skeleton.vue')['default']
  }
}
