build:
	pnpm run build
	gzip -k dist/**/*.js
	brotli -k dist/**/*.js

lint:
	pnpm run lint

serve: build serve-no-build

serve-no-build:
	# https://github.com/http-party/http-server
	http-server ./dist --brotli --gzip