set fallback

prepare:
	cd .. && just build-grammar

build: prepare
	pnpm run build
	gzip -k dist/**/*.js
	brotli -k dist/**/*.js

test: prepare
	pnpm run type-check

serve: build serve-no-build

serve-no-build:
	# https://github.com/http-party/http-server
	http-server ./dist --brotli --gzip