pre-run: compile-grammar

compile-grammar:
	./scripts/compile-lezer.ts ./src/grammars/dicexp.grammar

build: pre-run

test: pre-run
	pnpm exec vitest --dir=test --run

bench: pre-run
	pnpm exec vitest bench --dir=test --run