# see: https://github.com/actions/starter-workflows/blob/main/pages/static.yml
# see: https://github.com/actions/deploy-pages

name: 部署 Playground 至 Pages

on:
  push:
    branches: [main]

  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 6.32.9
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: "19"
          cache: pnpm
      - name: Setup Pages
        uses: actions/configure-pages@v3
      - name: Setup Just
        uses: extractions/setup-just@v1
      - name: Install dependencies
        run: |
          cd internal/lezer
          pnpm i
          cd ${{ github.workspace }}/playground
          pnpm i
      - name: Build playground
        run: |
          cd playground
          just pre-build
          pnpm exec vite build --base="/${{ github.event.repository.name }}/"
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: ./playground/dist

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2
