# see: https://github.com/actions/starter-workflows/blob/main/pages/static.yml
# see: https://github.com/actions/deploy-pages

name: 测试

on:
  push:
    branches: [main]

  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 24
      - uses: pnpm/action-setup@v4
        name: Install pnpm
        with:
          version: "10.15.1"
          run_install: false
      - name: Get pnpm store directory
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_ENV
      - uses: actions/cache@v4
        name: Setup pnpm cache
        with:
          path: ${{ env.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: Setup Just
        uses: extractions/setup-just@v1

      - name: Install dependencies
        run: |
          pnpm i -r

      - name: Run tests
        run: |
          just test-all
